title: 二条律师｜日拱一卒
subtitle: "日拱一卒"
description: "二条律师的个人网站 — 法律、思考、工具、暴论，混排输出。"
keywords: "律师,法律,二条,思考,工具"
author: 二条
language: zh-CN
timezone: "Asia/Shanghai"

# URL
url: https://ertiao.com
root: /
permalink: writing/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archive
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
index_generator:
  exclude:
    - cases
  path: ""
  per_page: 8
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
  reload: reload
  caveman: caveman
  law: law
  tools: tools
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
use_date_for_updated: false

# Pagination
per_page: 8
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Extensions
theme: fluid

# Feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: "..."
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

# Search
search:
  path: search.xml
  field: post
  content: true
  format: html
