# Stellar 主题覆盖配置 - 二条律师

logo:
  avatar: '/img/avatar.png'
  title: '二条律师'
  subtitle: '修辞立其诚'

menubar:
  columns: 5
  items:
    - id: home
      theme: '#1BCDFC'
      title: 首页
      url: /
    - id: writing
      theme: '#3DC550'
      title: 写作
      url: /writing/
    - id: cases
      theme: '#FA6400'
      title: 案例
      url: /categories/cases/
    - id: projects
      theme: '#F44336'
      title: 项目
      url: /projects/
    - id: about
      theme: '#9C27B0'
      title: 关于
      url: /about/

site_tree:
  home:
    menu_id: home
    leftbar: welcome, recent
    rightbar:
  index_blog:
    base_dir: blog
    menu_id: home
    leftbar: welcome, recent
    rightbar:
  post:
    menu_id: home
    leftbar: related, recent
    rightbar: toc
  page:
    leftbar: recent
    rightbar: toc
  error_page:
    menu_id: home
    '404': '/404.html'

article:
  type: story
  indent: true
  auto_excerpt: 200

search:
  service: local_search
  local_search:
    field: title
    path: /search.json
    content: false

style:
  prefers_theme: auto
  color:
    theme: 'hsl(207, 90%, 54%)'
    accent: 'hsl(14, 100%, 57%)'
    link: 'hsl(207, 90%, 54%)'

footer:
  social:
    github:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/social/08a41b181ce68.svg"/>'
      url: https://github.com/azrzsthl
  sitemap:
    - title: 导航
      items:
        - '[首页](/)'
        - '[写作](/writing/)'
        - '[案例](/categories/cases/)'
        - '[项目](/projects/)'
        - '[关于](/about/)'
    - title: 分类
      items:
        - '[一点小研究](/categories/law/)'
        - '[浅薄思考](/categories/reload/)'
        - '[碎碎念](/categories/caveman/)'
        - '[工具](/categories/tools/)'
  content: |
    本站由 [{author.name}](/) 使用 [{theme.name} {theme.version}]({theme.tree}) 主题创建。
